[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini-options]
addopts = "--cov=kelpickle"
testpaths = [
    "tests"
]

[tool.tox]
legacy_tox_ini="""
[tox]
envlist = py310, flake8, mypy
isolated_build = True

[testenv]
commands =
    python -m pip install pip -U
    pip install .[dev]
    pytest


[testenv:mypy]
deps=mypy
commands=mypy kelpickle

[testenv:flake8]
deps=flake8
commands = flake8 kelpickle tests

[flake8]
max-file-length = 160
"""

[tool.mypy]
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs  = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
strict_equality = true
pretty = true
show_traceback = true
raise_exceptions = true
html_report = "./mypy_reports/report.html"
junit_xml = "./mypy_reports/report.xml"